### ISSUE TITLE
Encourage users to try deactivating after a period of time without errors

### ISSUE THREAD

**Issue by desrosj** [WordPress/jquery-migrate-helper#10]
The plugin was meant to solve only one specific issue: a plugin having old jQuery code that caused JavaScript execution to stop, breaking sites. However, there was [another issue in 5.5](https://core.trac.wordpress.org/ticket/50999) that also happened to be fixed by this plugin because it defines `CONCATENATE_SCRIPTS` to `false`.

Plugin authors that encountered this issue encouraged users to utilize this plugin to fix the issue before deciding to push out their own update when they felt the issue was becoming a burden on their support. While it was great that this plugin was already available to help fix that issue as well, this inflated the active install number, making it a poor metric for gauging how many sites are experiencing issues as a result of disabling jQuery Migrate by default. The plugin currently sits around 100k active installs.

I was thinking about ways that we could get the active install metric to be meaningful again, I think that we should try the following:
- Log when an error is encountered in some way or count the number of pages loaded by administrators without encountering an error in jQuery Migrate.
- Display an admin notice to users with `activate_plugins` that they should try disabling the plugin when X days or X pages are loaded with an explanation of why it may now be safe to disable and what to look for.

Hopefully, plugins and themes have updated their code to use the more modern jQuery features and users will be able to leave the plugin deactivated. If they are still encountering an issue, they can reactivate and continue on. The hope is that adding this will decrease the number of active installs over the next month or two and make the active install number a meaningful metric again as we continue down the upgrading jQuery roadmap.

**Comment by Clorith** [comment]
I think this makes sense, it also adds a bit more push for users to engage with authors if they know that a problem is recurring frequently I think.
