### ISSUE TITLE
Review the text for the warnings

### ISSUE THREAD

**Issue by azaozz** [WordPress/jquery-migrate-helper#2]
Ideally the text for the two warnings can be polished a bit. The first (top) one is more of a help, can be dismissed, and is shown only on the Dashboard. The second is for when a deprecated code is detected and can appear on any wp-admin screen.

![warnings](https://user-images.githubusercontent.com/743931/89575545-cb343b00-d7e2-11ea-9af5-555c210c8c86.png)

**Comment by joyously** [comment]
You are currently using a helper Javascript for your theme and plugins that use an old version of jQuery. Please check if you still need this helper by disabling this plugin or asking plugin/theme authors.
While logged in to the WP backend, you will see warnings about deprecated scripts.
To find out more about what plugin or theme is causing issues for the public part of **your** site, please consult your Console Log.

**Comment by joyously** [comment]
A deprecated function means that the function will be removed in a later version, and should be replaced with more modern code.

**Comment by marybaum** [comment]
**jQuery Migrate Helper**
Right now you are using a helper JavaScript that your theme or one or more of your plugins installed to help your site run some old code, but it's possible you no longer need it. 

To check, please deactivate the jQuery Migrate Helper plugin and then browse the WP backend. If you see errors or warnings about deprecated* scripts, you should reactivate jQuery Migrate Helper.

*A script, a file, or some other piece of code is **deprecated** when its developers are in the process of replacing it with more modern code or removing it entirely from its environment. 
If you get a warning, you should check the theme or plugin that generated it for an update—there will very likely be one you can install.

**jQuery Migrate Helper: Warnings encountered**
This page generated the following warnings:

1. http://site.test/wp-content/plugins/tweaks.js:jQuery.fn.live() is deprecated*
2. http://site.test/wp-content/plugins/tweaks.js:jQuery.fn.live() is deprecated*

Please make sure you're using the latest version of all of your plugins, and your theme. If you are, you might want to ask their developers for an update.

*A script, a file, or some other piece of code is **deprecated** when its developers are in the process of replacing it with more modern code or removing it entirely from its environment. 

If you get a warning, you should check the theme or plugin that generated it for an update—there will very likely be one you can install.

**Comment by abhansnuk** [comment]
For ‘WP backend’ could we say ‘WordPress Dashboard’?

**Comment by azaozz** [comment]
Hmm, why repeating the "what does deprecated means" at the bottom in both warnings? Seems enough to show only in the top one, perhaps? Also not sure about having line breaks (br tags), don't seem needed?

Another, somewhat unclear bit may be: "Right now you are using a helper JavaScript that your theme or one or more of your plugins installed to help your site run some old code...".

Maybe something along this:

"Right now you are using the Enable jQuery Migrate Helper plugin to enable support for old JavaScript code that uses deprecated functions in the jQuery JavaScript library. You will see warnings about these functions while using WordPress administration, but they will not be shown on the front-end of your site. To check if there are any warnings generated by your theme please look in the browser console.

If you get warnings, you should check the theme or plugin that generated them for an update. There will very likely be one you can install. When you have updated your plugins and themes, and there are no more warnings, please deactivate Enable jQuery Migrate Helper.

*A script, a file, or some other piece of code is deprecated when its developers are in the process of replacing it with more modern code or removing it entirely."

And the second warning:

"This page generated the following warnings:

- http://site.test/wp-content/plugins/tweaks.js: jQuery.fn.live() is deprecated
- http://site.test/wp-content/plugins/tweaks.js: jQuery.fn.live() is deprecated

Please make sure you are using the latest version of all of your plugins, and your theme. If you are, you may want to ask the developers of the code mentioned in the warnings for an update."

**Comment by azaozz** [comment]
Proposed changes look like this:

![warnings-2](https://user-images.githubusercontent.com/743931/89741621-878e3b00-da47-11ea-862f-7c646e7eda71.png)
