### ISSUE TITLE
erroredFunction should also handle null?

### ISSUE THREAD

**Issue by fliespl** [WordPress/jquery-migrate-helper#29]
When error as such appears in log:  Uncaught TypeError: Cannot read property 'xxx' of undefined

JQMH also errors out, because erroredFunction  is null and null is equal to object.

```
                if ( typeof erroredFunction !== 'object' || typeof erroredFunction[1] === "undefined" || -1 === jQueryFunctions.indexOf( erroredFunction[1] ) ) {
                    return true;
                }
```

**Error caused:**

```
Uncaught TypeError: Cannot read property '1' of null
    at window.onerror ((index):139)
window.onerror @ (index):139
error (async)
(anonymous) @ (index):115
```

Probably null should also be checked, when no matches are found?

**Comment by bndn** [comment]
This error is <a href="https://wordpress.org/support/topic/errors-in-fatal_error_handler/">reported on the WordPress support forum too</a>. We have to add a condition to the line 289 of `wp-content/plugins/enable-jquery-migrate-helper/class-jquery-migrate-helper.php` to fix it:

`if ( erroredFunction === null || typeof erroredFunction !== 'object' || typeof erroredFunction[1] === "undefined" || -1 === jQueryFunctions.indexOf( erroredFunction[1] ) ) {`
