### ISSUE TITLE
Add a method for average users to discover issues in the front-end

### ISSUE THREAD

**Issue by Clorith** [WordPress/jquery-migrate-helper#8]
Currently, the plugin surfaces any warnings with an admin notice in the back-end of your site, but does nothing for the front end.

Observations tell us that although a lot of negatively impacted JavaScript code was in the backend, a not unsubstantial amount of the reported issues have been front-end facing as well.

For the non-technical users, it would be beneficial to surface these as well somehow, my initial thought is to leverage the admin bar, as it provides a non-intrusive manner of which to add a dropdown detailing the plugin and error ,much like the backend one does, but without all the explanations around it.

Query Monitor already does something similar to this for JavaScript errors in general, and although one could recommend it, it would be like taking a hammer to swat a fly, as the saying goes, and may lead to added confusion for the average user.

**Comment by Clorith** [comment]
If this method is adopted, the regular admin notice could also support timed dismissals, on the same basis as the existing notice in there.

A user could dismiss the notice explaining what deprecations are and what triggered them on this page, and only have them pop up in the admin bar. The more prominent warning would re-appear after 2 weeks, but they'd be able to re-dismiss it again at that point if so desired.

**Comment by Clorith** [comment]
Simple display thoughts

The default look, the menu item is always shown, as a persistent menu item will let you restore admin notices. Doing so will make is so users can dismiss both types of admin notices, but still get warnings in a non-intrusive way.
![admin bar showing menu item for "jQuery migrate"](https://user-images.githubusercontent.com/468735/90977558-95af8180-e546-11ea-8929-9f720414387d.png)

If warnings are found, the menu item turns red, and the label is changed slightly to show that there are warnings, and how many warnings there are. The indicator color helps with identifying that something has changed, the added label and numeric representation will help those who have varying degrees of colorblindness. Would use the WP number badge, the parenthesis is just for representation right now.
![admin bar showing red warning label with numeric representation in parenthesis](https://user-images.githubusercontent.com/468735/90977541-6d278780-e546-11ea-9574-62fc0ec309ae.png)

The bit I'm a bit uncertain of, is the warnings them selves, I've included two examples here
![menu expanded to show warnings detected](https://user-images.githubusercontent.com/468735/90977621-03f44400-e547-11ea-80e1-d64d9edf219d.png)

The first one is what is shown in the admin notice, but this feels a bit "wordy" in the dropdown of an admin bar entry, the 2nd one just strips away the domain (if the same as the site).

The third menu item is the persistent one, that allows the user to restore admin notices, just in case they wanted to re-read the description or accidentally removed the existing larger warnings.

Alongside this, menu items are a bit finicky at times, so I wonder if adding a click to copy on the warnings in that menu item would make sense, appending a copy-icon or similar to indicate the possibility, this would make it easier to provide the actual warning to your plugin or theme authors as well.

**Comment by desrosj** [comment]
I think including the notices in the dropdown is not the best idea. However, I am in favor of having something in the admin bar. I am drawn to the first two screenshots.

I'm not sure how notices are recorded or logged, but what if a tab in Site Health or a page under Tools was introduced? Then, the admin bar could link to that location and display the notices encountered.

**Comment by Clorith** [comment]
Currently, no notices are logged (that would change by doing #10), but I kind of like that idea, I (ironically enough) hadn't even considered adding it to Site Health, but it makes sense to extend this, that way it could also be hooked into the weekly check that changes the status, I even think it's reasonable to say that we consider it a critical item to resolve deprecation issues before the next WP version rolls out?

**Comment by desrosj** [comment]
> I even think it's reasonable to say that we consider it a critical item to resolve deprecation issues before the next WP version rolls out?

I think that's entirely reasonable.
