### ISSUE TITLE
jQuery Migrate Helper - Warnings encountered - but none displayed -  when Test jQuery Updates is activated

### ISSUE THREAD

**Issue by bobbingwide** [WordPress/jquery-migrate-helper#9]
It's not spelt out anywhere whether or not you can use both jQuery Migrate Helper and Test jQuery Updates together.
My experience is that you can't.

Problems arise when the Test jQuery Updates settings are: jQuery version: 3.5.1, jQuery Migrate: Enable

![image](https://user-images.githubusercontent.com/2474435/91656253-5685b100-eaaf-11ea-916d-6b4c337c2039.png)

Also, when jQuery Migrate is set to Disable, then 
jquery-3.5.1.js?ver=3.5.1:4046 jQuery.Deferred exception: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at HTMLDocument.<anonymous> (https://s.b/cwiccer/wp-content/plugins/enable-jquery-migrate-helper/js/deprecation-notice.js?ver=5.5:40:33)
    at mightThrow (https://s.b/cwiccer/wp-content/plugins/wp-jquery-update-test/assets/jquery-3.5.1.js?ver=3.5.1:3762:29)
    at process (https://s.b/cwiccer/wp-content/plugins/wp-jquery-update-test/assets/jquery-3.5.1.js?ver=3.5.1:3830:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.5.1.js?ver=3.5.1:4046
process @ jquery-3.5.1.js?ver=3.5.1:3834
setTimeout (async)
(anonymous) @ jquery-3.5.1.js?ver=3.5.1:3868
fire @ jquery-3.5.1.js?ver=3.5.1:3496
fireWith @ jquery-3.5.1.js?ver=3.5.1:3626
fire @ jquery-3.5.1.js?ver=3.5.1:3634
fire @ jquery-3.5.1.js?ver=3.5.1:3496
fireWith @ jquery-3.5.1.js?ver=3.5.1:3626
ready @ jquery-3.5.1.js?ver=3.5.1:4106
completed @ jquery-3.5.1.js?ver=3.5.1:4116
plugins.php?page=wp-jquery-update-test&jqtest-settings-saved:533 WordPress jQuery: 3.5.1, Migrate: not available, UI: not available
jquery-3.5.1.js?ver=3.5.1:4055 Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLDocument.<anonymous> (deprecation-notice.js?ver=5.5:40)
    at mightThrow (jquery-3.5.1.js?ver=3.5.1:3762)
    at process (jquery-3.5.1.js?ver=3.5.1:3830)

### Workaround
- Deactivate jQuery Migrate Helper

**Comment by Clorith** [comment]
Hiya,

This would be expected to fail, if you are using jQuery 3.x, then the migrate script made for version 1.x will cause issues. There is no compatibility between the versions for 1.x and 3.x, the latter having its own migrate script (which is planned for inclusion when jQuery it self is upgraded in core as well)

IT's not stated anywhere explicitly that they do not work together, correct, but the Enable jQuery Migrate Helper plugin (this one) is meant as a temporary fix for WordPress 5.5

I would say that the conflict here is "acceptable", and there's no changes that need to be made, as anyone doing testing with the Test jQuery Update plugin are already experimenting, but would of course like to hear suggestions if there are any on how better to deal with this. I will add that adding exceptions to plugins that cause conflicts quickly becomes a slippery slope though.

**Comment by Clorith** [comment]
Closing this as the breaking effect is expected when mixing the jQuery Update tester on a newer version than what jQuery Migrate supports.
